---

ansible_network_os: arista.eos.eos
ansible_connection: httpapi                                                             # using eAPI
ansible_httpapi_port: 443
ansible_httpapi_use_ssl: true
ansible_httpapi_validate_certs: false
ansible_httpapi_ciphers: AES256-SHA:DHE-RSA-AES256-SHA:AES128-SHA:DHE-RSA-AES128-SHA    # SSLV3_ALERT_HANDSHAKE_FAILURE
                                                                                        # https://arista.my.site.com/AristaCommunity/s/article/Python-3-10-and-SSLV3-ALERT-HANDSHAKE-FAILURE-error
ansible_become: yes
ansible_become_method: enable

# ansible_connection: ansible.netcommon.network_cli                                     # work over network_cli
