- name: "Demonstrate connecting to network"
  hosts: network
  gather_facts: no

  tasks:
    ###
    # Collect data
    #
    - name: Gather facts (eos)
      arista.eos.eos_facts:
      when: ansible_network_os == 'arista.eos.eos'

    - name: Gather facts (ios)
      cisco.ios.ios_facts:
      when: ansible_network_os == 'cisco.ios.ios'

    - name: Gather facts (junos)
      junipernetworks.junos.junos_facts:
      when: ansible_network_os == 'junipernetworks.junos.junos'

    ###
    # Demonstrate variables
    #
    - name: Display some facts
      debug:
        msg: "The hostname is {{ ansible_net_hostname }} and the OS is {{ ansible_net_version }}"

    - name: Facts from a specific host
      debug:
        var: hostvars['tpe6-igw1']

    - name: Write facts to disk using a template
      copy:
        content: |
          #jinja2: lstrip_blocks: True
          EOS device info:
          
            {% for host in groups['eos'] %}
            Hostname: {{ hostvars[host].ansible_net_hostname }}
            Version:  {{ hostvars[host].ansible_net_version }}
            Model:    {{ hostvars[host].ansible_net_model }}
            Serial:   {{ hostvars[host].ansible_net_serialnum }}
            ----------------------
            {% endfor %}

          IOS device info:

            {% for host in groups['ios'] %}
            Hostname: {{ hostvars[host].ansible_net_hostname }}
            Version:  {{ hostvars[host].ansible_net_version }}
            Model:    {{ hostvars[host].ansible_net_model }}
            Serial:   {{ hostvars[host].ansible_net_serialnum }}
            ----------------------
            {% endfor %}

          junos device info:

            {% for host in groups['junos'] %}
            Hostname: {{ hostvars[host].ansible_net_hostname }}
            Version:  {{ hostvars[host].ansible_net_version }}
            Model:    {{ hostvars[host].ansible_net_model }}
            Serial:   {{ hostvars[host].ansible_net_serialnum }}
            ----------------------
            {% endfor %}
        dest: /tmp/switch-facts
      run_once: yes

    ###
    # Get running configuration
    #

    - name: Backup switch (eos)
      arista.eos.eos_config:
        backup: yes
        backup_options:
          dir_path: /tmp/backups/{{ inventory_hostname }}/
      register: backup_eos_location
      when: ansible_network_os == 'arista.eos.eos'

    - name: backup switch (junos)
      junipernetworks.junos.junos_config:
        backup: yes
        backup_options:
          dir_path: /tmp/backups/{{ inventory_hostname }}/
      register: backup_junos_location
      when: ansible_network_os == 'junipernetworks.junos.junos'

    - name: backup switch (ios)
      cisco.ios.ios_config:
        backup: yes
        backup_options:
          dir_path: /tmp/backups/{{ inventory_hostname }}/
      register: backup_ios_location
      when: ansible_network_os == 'cisco.ios.ios'
    
    # - name: Display backup_ios_location
    #   debug:
    #     var: backup_ios_location

    - name: Create backup dir
      file:
        path: "/tmp/backups/{{ inventory_hostname }}"
        state: directory
        recurse: yes

    # - name: Copy backup files into /tmp/backups/ (eos)
    #   copy:
    #     src: "{{ backup_eos_location.backup_path }}"
    #     dest: "/tmp/backups/{{ inventory_hostname }}/{{ inventory_hostname }}.bck"
    #   when: ansible_network_os == 'arista.eos.eos'

    # - name: Copy backup files into /tmp/backups/ (junos)
    #   copy:
    #     src: "{{ backup_junos_location.backup_path }}"
    #     dest: "/tmp/backups/{{ inventory_hostname }}/{{ inventory_hostname }}.bck"
    #   when: ansible_network_os == 'junipernetworks.junos.junos'

    # - name: Copy backup files into /tmp/backups/ (ios)
    #   copy:
    #     src: "{{ backup_ios_location.backup_path }}"
    #     dest: "/tmp/backups/{{ inventory_hostname }}/{{ inventory_hostname }}.bck"
    #   when: ansible_network_os == 'cisco.ios.ios'