---

# Ansible Playbook to upload new Cisco IOS
# Only upload file if the current IOS version is different

- name: Upload new CISCO IOS files
  hosts: ios
  gather_facts: no

  vars:
    upgrade_ios_version: 15.2(7)E6                  # Update the target version 
    new_image: c2960x-universalk9-tar.152-7.E6.tar  # Update the target image
    file_size: 40580                                # Update the size in kB
    ansible_command_timeout: 1200                   # 20 mins

  tasks:
    - name: CHECK CURRENT VERSION
      ios_facts:
        gather_subset: hardware

    - debug:
        msg:
        - "Current version is {{ ansible_net_version }}"
        - "Upgrade image is 15.2(7)E6"

    - name: CONFIRM CURRENT IMAGE ARE DIFFERENT
      assert:
        that: "ansible_net_version != upgrade_ios_version"  
        fail_msg: "FAIL - Unit already at new image"
        success_msg: "PASS - Unit proceeds upgrade"

    # - debug:
    #     msg:
    #     - "New IOS and current IOS are different."
 
    #   when: ansible_net_version != upgrade_ios_version

    - name: SET VARIABLES FOR DEVICE FILE SYSTEMS
      set_fact:
        free_space: "{{ansible_net_filesystems_info['flash:']['spacefree_kb']}}"
        file_destination: "{{ ansible_net_filesystems[0] + new_image }}"

    - debug:
        msg: "AVAILABLE FREE MEMORY SPACE = {{ free_space }} kb"

    - name: CONFIRM DEVICE HAS ENOUGH FREE MEMORY SPACE BEFORE TRANSFER
      assert:
        that: "{{ free_space }} > {{ file_size }}"  # convert to kbps
        fail_msg: "FAIL - Not enough space available for upload"
        success_msg: "PASS - Enough space available for upload"

    - name: ACTIVATE CI SCP SERVER FEATURE # Ensure device has the scp feature activated.
      ios_config:
        commands: ip scp server enable

    # - debug:
    #     msg: "UPLOAD DESTINATION = {{ file_destination }}"

    - name: COPY_NEW_IOS_FROM_FTP (10.114.60.13)
      cli_command:
         command: 'copy scp://otan:{{ansible_ssh_pass}}@10.114.60.13/images/{{ new_image }} {{ file_destination }}'
         check_all: True
         prompt:
           - 'Destination filename'
         answer:
           - '{{ new_image }}'

    # - name: Copy new IOS from ansible controll node to Network devices
    #   net_put:
    #     src: '~/images/{{ new_image }}'
    #     dest: '{{ file_destination }}'

    - debug:
        msg: "UPLOAD CONFIRMATION-New ios image uploaded successfully."