---
- name: Get Device Facts
  hosts: junos
  connection: local
  gather_facts: no

  tasks:
    - name: Checking NETCONF connectivity
      wait_for: 
        host: "{{ ansible_host }}"
        port: 830
        timeout: 5
           

    - name: Retrieve facts from a Junos device
      connection: juniper.device.pyez
      juniper.device.facts:
        savedir: "/tmp/backups/"

    - name: Print version
      debug:
        var: junos.version








  # tasks:
  # - name: Retrieve facts from a Junos device
  #   connection: netconf
  #   junipernetworks.junos.junos_facts:
  #     gather_subset:
  #     - min

  # - name: Print version
  #   debug:
  #     var: ansible_net_version
  