---

- name: Upgrade a Junios Device
  hosts: junos
 
  tasks:
  - junos_facts:
      host: vsrx
      provider: "{{ netconf }}"
  - junos_package: 
      src: ~/path/to/file/12.1X47-D10.4-domestic-signed.tgz
      reboot: yes
      version: "{{ package }}"	 
      provider: "{{ netconf }}"
 
  - include: verify_connectivity.yml
    when: version != "{{ package }}"

- name: check connectivity to internet
  wait_for:
         port: 830
         host: "{{inventory_hostname}}"
         timeout: 300

- junos_command:
         commands: ping 8.8.8.8 count 5
         provider: "{{netconf}}"
  register: result

- fail: msg="ping failed"
  when: result.stdout[0]['ping-results']['probe-results-summary']['packet-loss'] != "0"