---
- name: Get Device Facts
  hosts: junos
  connection: juniper.device.pyez
  gather_facts: no

  tasks:
    - name: Checking NETCONF connectivity
      wait_for: 
        host: "{{ ansible_host }}"
        port: 830
        timeout: 5

    - name: Create backup dir
      file:
        path: "/tmp/backups/{{ inventory_hostname }}"
        state: directory
        recurse: yes  

    - name: Retrieve facts from a Junos device
      juniper.device.facts:
        savedir: "/tmp/backups/{{ inventory_hostname }}"
        config_format: "set"
      register: result

    - name: Print version
      debug:
        var: result.ansible_facts.junos.config

    # - name: Get Hardware inventory
    #   juniper.device.command:
    #     commands: "show chassis hardware"
    #     dest_dir: "/tmp/backups/{{ inventory_hostname }}"
    #   register: hardware
    
    # - name: Print HW
    #   debug:
    #     var: hardware.stdout_lines






  # tasks:
  # - name: Retrieve facts from a Junos device
  #   connection: netconf
  #   junipernetworks.junos.junos_facts:
  #     gather_subset:
  #     - min

  # - name: Print version
  #   debug:
  #     var: ansible_net_version
  